name: CI/CD - Validar y Desplegar a Render

on:
  push:
    branches: [ master ] # O usa [ main ] según el nombre de tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Generar Prisma y Compilar
        run: |
          npx prisma generate
          npm run build

      - name: Notificar a Render para publicar
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
